[pyprland]

plugins = [
  "scratchpads",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "60% 75%"

[scratchpads.file]
animation = "fromTop"
command = "kitty --class kitty-yazi yazi"
class = "kitty-yazi"
size = "60% 75%"
