[pyprland]

plugins = [
  "scratchpads",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "70% 80%"
max_size = "1920px 100%"
margin = 50

[scratchpads.files]
animation = "fromTop"
command = "nemo"
class = "nemo-dropterm"
size = "70% 80%"
max_size = "1920px 100%"
margin = 50
